repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black-jupyter

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    - id: pyupgrade

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.29.1]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    - id: codespell
      files: ^.*\.(py|ipynb|md|rst)$
