dist: xenial
language: python
cache: pip
python: '3.7'
install:
- pip install --upgrade pip
- pip install --upgrade -q -r binder/requirements.txt
- pip freeze
script:
  - pytest

stages:
  - test
  - name: binder
    if: (branch = master) AND (NOT (type IN (pull_request)))

jobs:
  include:
  - stage: test
  - stage: binder
    before_install: skip
    install: skip
    script:
      # Use Binder build API to trigger repo2docker to build image
      - bash binder/trigger_binder.sh https://mybinder.org/build/gh/matthewfeickert/Statistics-Notes/"${TRAVIS_BRANCH}"
